In [18]:
import pandas as pd

df=pd.read_csv('dataset.csv')

df.columns

numerical_data=['customer_id', 'age', 'annual_income', 'months_active',

       'avg_monthly_spend', 'purchase_frequency', 'avg_order_value',

       'discount_usage_rate', 'return_rate', 'browsing_time_minutes',

       'support_interactions',

       'total_spend', 'engagement_score']

categorical_data=['payment_method', 'region']   

y=['customer_segment']    

from sklearn.preprocessing import StandardScaler,OneHotEncoder

from sklearn.pipeline import Pipeline

numeric_pipeline=Pipeline(steps=[('scaler',StandardScaler())])

categorical_pipeline=Pipeline(steps=[('encode',OneHotEncoder(handle_unknown='ignore'))])

from sklearn.compose import ColumnTransformer

features=ColumnTransformer(transformers=[('num',numeric_pipeline,numerical_data),('cat',categorical_pipeline,categorical_data)])

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import classification_report, confusion_matrix

In [20]:
from sklearn.model_selection import train_test_split
X=df.drop(columns=['customer_segment'])
Y=df['customer_segment']
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

## Classification Metrics for Logistic Regression

Classification Report

In [21]:

lr=Pipeline(steps=[('feature',features),('Classification',LogisticRegression())])
lr.fit(x_train,y_train)
y_predict=lr.predict(x_test)
report=classification_report(y_test,y_predict,output_dict=True)
result=pd.DataFrame(report).transpose()
result

              precision    recall  f1-score     support
High_Value     0.760000  0.730769  0.745098   26.000000
Loyal          0.657895  0.657895  0.657895   38.000000
Occasional     0.696970  0.884615  0.779661   78.000000
Regular        0.581395  0.396825  0.471698   63.000000
accuracy       0.673171  0.673171  0.673171    0.673171
macro avg      0.674065  0.667526  0.663588  205.000000
weighted avg   0.662203  0.673171  0.658064  205.000000

Confusion Matrix

In [22]:
confusion_matrix(y_test,y_predict)

array([[19,  5,  1,  1],
       [ 4, 25,  1,  8],
       [ 0,  0, 69,  9],
       [ 2,  8, 28, 25]])

## Classification Matrix for Gaussian Naive Bayes

Classification Report

In [23]:

nb=Pipeline(steps=[('feature',features),('Classification',GaussianNB())])
nb.fit(x_train,y_train)
y_predict=nb.predict(x_test)
report=classification_report(y_test,y_predict,output_dict=True)
result=pd.DataFrame(report).transpose()
result

              precision    recall  f1-score     support
High_Value     0.727273  0.615385  0.666667   26.000000
Loyal          0.549020  0.736842  0.629213   38.000000
Occasional     0.796610  0.602564  0.686131   78.000000
Regular        0.520548  0.603175  0.558824   63.000000
accuracy       0.629268  0.629268  0.629268    0.629268
macro avg      0.648363  0.639491  0.635209  205.000000
weighted avg   0.657083  0.629268  0.633988  205.000000

Confusion Matrix

In [ ]:
confusion_matrix(y_test,y_predict)

## Classification Metrics for KNN

Classifcation Report

In [24]:

kn=Pipeline(steps=[('feature',features),('Classification',KNeighborsClassifier())])
kn.fit(x_train,y_train)
y_predict=kn.predict(x_test)
report=classification_report(y_test,y_predict,output_dict=True)
result=pd.DataFrame(report).transpose()
result

              precision    recall  f1-score     support
High_Value     0.684211  0.500000  0.577778   26.000000
Loyal          0.395833  0.500000  0.441860   38.000000
Occasional     0.553398  0.730769  0.629834   78.000000
Regular        0.371429  0.206349  0.265306   63.000000
accuracy       0.497561  0.497561  0.497561    0.497561
macro avg      0.501218  0.484280  0.478695  205.000000
weighted avg   0.484859  0.497561  0.476362  205.000000

Confusion Matrix

In [ ]:
confusion_matrix(y_test,y_predict)